/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoquest;

/**
 *
 * @author Paiva Morais
 */
public class InserirVouF extends javax.swing.JPanel {

    /**
     * Creates new form InserirVouF
     */
    public InserirVouF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        homeVouF = new javax.swing.JButton();
        disciplinaVouF = new javax.swing.JComboBox<>();
        temaVouF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dificuladeVouf = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        enviarVouF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enunciadoVouF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alt1vouf = new javax.swing.JTextField();
        alt2vouf = new javax.swing.JTextField();
        alt3vouf = new javax.swing.JTextField();
        alt4vouf = new javax.swing.JTextField();
        alt5vouf = new javax.swing.JTextField();
        alt6vouf = new javax.swing.JTextField();
        alt7vouf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alt1verdadeiro = new javax.swing.JRadioButton();
        alt1falso = new javax.swing.JRadioButton();
        alt2verdadeiro = new javax.swing.JRadioButton();
        alt2falso = new javax.swing.JRadioButton();
        alt3verdadeiro = new javax.swing.JRadioButton();
        alt3falso = new javax.swing.JRadioButton();
        alt4verdadeiro = new javax.swing.JRadioButton();
        alt5verdadeiro = new javax.swing.JRadioButton();
        alt6verdadeiro = new javax.swing.JRadioButton();
        alt7verdadeiro = new javax.swing.JRadioButton();
        alt4falso = new javax.swing.JRadioButton();
        alt5falso = new javax.swing.JRadioButton();
        alt6falso = new javax.swing.JRadioButton();
        alt7falso = new javax.swing.JRadioButton();

        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1028, 594));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 87, 155));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Banco de Questões");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setAlignmentX(0.5F);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        homeVouF.setBackground(new java.awt.Color(33, 150, 243));
        homeVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        homeVouF.setForeground(new java.awt.Color(255, 255, 255));
        homeVouF.setText("HOME");
        homeVouF.setAlignmentX(0.5F);
        homeVouF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeVouF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeVouFActionPerformed(evt);
            }
        });

        disciplinaVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        disciplinaVouF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina a disciplina:", "Aplicações para Web", "Arquitetura de Sistemas Digitais", "Linguagem de Programação - JAVA", "Manutenção de Computadores", "Biologia", "Filosofia", "Física", "Geografia", "História", "Matemática", "Português", "Química", "Sociologia", "Outra" }));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Digite o tema:");

        dificuladeVouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dificuladeVouf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defina o nível de dificuldade da questão:", "Fácil", "Mediana", "Díficil" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temaVouF)
                    .addComponent(disciplinaVouF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dificuladeVouf, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinaVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temaVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuladeVouf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A ferramenta que produz provas de maneira simples e funcional");

        enviarVouF.setBackground(new java.awt.Color(33, 150, 243));
        enviarVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enviarVouF.setForeground(new java.awt.Color(255, 255, 255));
        enviarVouF.setText("ENVIAR");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Digite o enunciado da questão:");

        enunciadoVouF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        enunciadoVouF.setForeground(new java.awt.Color(153, 153, 153));
        enunciadoVouF.setText("DIGITE O TEXTO AQUI.");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Digite as alternativas:");

        alt1vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt1vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt1vouf.setText("DIGITE O TEXTO AQUI.");

        alt2vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt2vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt2vouf.setText("DIGITE O TEXTO AQUI.");

        alt3vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt3vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt3vouf.setText("DIGITE O TEXTO AQUI.");

        alt4vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt4vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt4vouf.setText("DIGITE O TEXTO AQUI.");

        alt5vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt5vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt5vouf.setText("DIGITE O TEXTO AQUI.");

        alt6vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt6vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt6vouf.setText("DIGITE O TEXTO AQUI.");

        alt7vouf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        alt7vouf.setForeground(new java.awt.Color(153, 153, 153));
        alt7vouf.setText("DIGITE O TEXTO AQUI.");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Verdadeiro");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Falso");

        alt1verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt1falso.setBackground(new java.awt.Color(255, 255, 255));

        alt2verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt2falso.setBackground(new java.awt.Color(255, 255, 255));

        alt3verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt3falso.setBackground(new java.awt.Color(255, 255, 255));

        alt4verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt5verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt6verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt7verdadeiro.setBackground(new java.awt.Color(255, 255, 255));

        alt4falso.setBackground(new java.awt.Color(255, 255, 255));

        alt5falso.setBackground(new java.awt.Color(255, 255, 255));

        alt6falso.setBackground(new java.awt.Color(255, 255, 255));

        alt7falso.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enunciadoVouF)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(alt2vouf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                                        .addComponent(alt3vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt4vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt5vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt6vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt7vouf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt1vouf))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(alt1verdadeiro)
                                        .addComponent(alt2verdadeiro)
                                        .addComponent(alt3verdadeiro)
                                        .addComponent(alt4verdadeiro)
                                        .addComponent(alt5verdadeiro)
                                        .addComponent(alt6verdadeiro)
                                        .addComponent(alt7verdadeiro))
                                    .addGap(65, 65, 65)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alt1falso)
                                .addComponent(jLabel5)
                                .addComponent(alt2falso)
                                .addComponent(alt3falso)
                                .addComponent(alt4falso)
                                .addComponent(alt5falso)
                                .addComponent(alt6falso)
                                .addComponent(alt7falso))
                            .addGap(40, 40, 40)))
                    .addComponent(enviarVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciadoVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt1vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt1verdadeiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt2vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt2verdadeiro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alt1falso)
                        .addGap(18, 18, 18)
                        .addComponent(alt2falso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt3vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt3verdadeiro)
                    .addComponent(alt3falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt4vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt4verdadeiro)
                    .addComponent(alt4falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt5vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt5verdadeiro)
                    .addComponent(alt5falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt6vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt6verdadeiro)
                    .addComponent(alt6falso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alt7falso)
                    .addComponent(alt7vouf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt7verdadeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarVouF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeVouFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeVouFActionPerformed
        FormInicial home = new FormInicial();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeVouFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alt1falso;
    private javax.swing.JRadioButton alt1verdadeiro;
    private javax.swing.JTextField alt1vouf;
    private javax.swing.JRadioButton alt2falso;
    private javax.swing.JRadioButton alt2verdadeiro;
    private javax.swing.JTextField alt2vouf;
    private javax.swing.JRadioButton alt3falso;
    private javax.swing.JRadioButton alt3verdadeiro;
    private javax.swing.JTextField alt3vouf;
    private javax.swing.JRadioButton alt4falso;
    private javax.swing.JRadioButton alt4verdadeiro;
    private javax.swing.JTextField alt4vouf;
    private javax.swing.JRadioButton alt5falso;
    private javax.swing.JRadioButton alt5verdadeiro;
    private javax.swing.JTextField alt5vouf;
    private javax.swing.JRadioButton alt6falso;
    private javax.swing.JRadioButton alt6verdadeiro;
    private javax.swing.JTextField alt6vouf;
    private javax.swing.JRadioButton alt7falso;
    private javax.swing.JRadioButton alt7verdadeiro;
    private javax.swing.JTextField alt7vouf;
    private javax.swing.JComboBox<String> dificuladeVouf;
    private javax.swing.JComboBox<String> disciplinaVouF;
    private javax.swing.JTextField enunciadoVouF;
    private javax.swing.JButton enviarVouF;
    private javax.swing.JButton homeVouF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField temaVouF;
    // End of variables declaration//GEN-END:variables
}
